name: example
description: "The Fuery example: a social feed against an in-memory server."
publish_to: 'none'

version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  fuery:
    path: ../
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
