name: fuery_hooks
description: "Hooks for Fuery: useQuery, useInfiniteQuery, useMutation, and useQueries for flutter_hooks."
version: 1.4.2
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  fuery: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
